#!/usr/bin/env bash
set -euo pipefail

protected_inputs=(
  MY_ART_COLLECTION_FIREBASE_ANDROID
  MY_ART_COLLECTION_INTERNAL_BETA_CRASHLYTICS
  MY_ART_COLLECTION_REMOTE_CONFIG
  MY_ART_COLLECTION_ANDROID_RELEASE_STORE_FILE
  MY_ART_COLLECTION_ANDROID_RELEASE_STORE_PASSWORD
  MY_ART_COLLECTION_ANDROID_RELEASE_KEY_ALIAS
  MY_ART_COLLECTION_ANDROID_RELEASE_KEY_PASSWORD
  ORG_GRADLE_PROJECT_MY_ART_COLLECTION_FIREBASE_ANDROID
  ORG_GRADLE_PROJECT_MY_ART_COLLECTION_INTERNAL_BETA_CRASHLYTICS
  ORG_GRADLE_PROJECT_MY_ART_COLLECTION_REMOTE_CONFIG
  ORG_GRADLE_PROJECT_MY_ART_COLLECTION_ANDROID_RELEASE_STORE_FILE
  ORG_GRADLE_PROJECT_MY_ART_COLLECTION_ANDROID_RELEASE_STORE_PASSWORD
  ORG_GRADLE_PROJECT_MY_ART_COLLECTION_ANDROID_RELEASE_KEY_ALIAS
  ORG_GRADLE_PROJECT_MY_ART_COLLECTION_ANDROID_RELEASE_KEY_PASSWORD
  DART_DEFINES
  ORG_GRADLE_PROJECT_DART_DEFINES
  ORG_GRADLE_PROJECT_dart-defines
  GOOGLE_APPLICATION_CREDENTIALS
  GOOGLE_SERVICES_JSON
  GOOGLE_CLOUD_PROJECT
  GCLOUD_PROJECT
  FIREBASE_CONFIG
  FIREBASE_TOKEN
  FIREBASE_PROJECT
  FIREBASE_APP_ID
  FIREBASE_GROUPS
  CRASHLYTICS_API_TOKEN
  REMOTE_CONFIG_API_KEY
  APK_PATH
  RELEASE_NOTES_FILE
  OPENAI_API_KEY
  ARCHIVALE_OPENAI_API_KEY
  OPENAI_ORG_ID
  OPENAI_PROJECT
  OPENAI_ALLOWED_DOMAINS
  ARCHIVALE_OPENAI_ALLOWED_DOMAINS
  OPENAI_RESPONSES_MODEL
  ARCHIVALE_OPENAI_RESPONSES_MODEL
  OPENAI_WEB_SEARCH_EXTERNAL_ACCESS
  ARCHIVALE_OPENAI_WEB_SEARCH_EXTERNAL_ACCESS
  OPENAI_WEB_SEARCH_CONTEXT_SIZE
  ARCHIVALE_OPENAI_WEB_SEARCH_CONTEXT_SIZE
  ANTHROPIC_API_KEY
  GOOGLE_API_KEY
  GEMINI_API_KEY
  GOOGLE_GENAI_API_KEY
)

if [[ "${1:-}" == "--list" && "$#" -eq 1 ]]; then
  printf '%s\n' "${protected_inputs[@]}"
  exit 0
fi
if [[ "$#" -ne 0 ]]; then
  echo "usage: check_android_ci_inputs.sh [--list]" >&2
  exit 2
fi

environment_names="$(node -e 'for (const name of Object.keys(process.env)) console.log(name)')"
for name in "${protected_inputs[@]}"; do
  if grep -Fxq "$name" <<< "$environment_names"; then
    echo "Unexpected protected Android build input: $name" >&2
    exit 1
  fi
done

echo "Android protected-input preflight passed: no Firebase, provider, deployment, or signing inputs are present."
